apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app # Updated name
  labels:
    app: my-springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: springboot-container
          image: shankar888/springboot-k8s-shankar:1.0 # Update with your actual Docker image and tag
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: my-springboot-app-service # Updated service name
spec:
  type: ClusterIP
  selector:
    app: my-springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8181
