apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-sm-deployment
  labels:
    app: springboot-sm-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-sm-app
  template:
    metadata:
      labels:
        app: springboot-sm-app
    spec:
      containers:
        - name: springboot-sm-container
          image: shankar888/springboot-k8s-sm:1.0 # Updated image name and tag
          ports:
            - containerPort: 8182
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-sm-service
spec:
  type: NodePort
  selector:
    app: springboot-sm-app
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8182
      nodePort: 5555
